// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository;

#nullable disable

namespace WebApp.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20250413184320_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("Entities.Forum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ForumGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Header")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IconUrl")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ForumGroupId");

                    b.ToTable("Forums");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ForumGroupId = 1,
                            Header = "Hata Raporlama",
                            IconUrl = "/images/icons/icon_report.png"
                        },
                        new
                        {
                            Id = 2,
                            ForumGroupId = 1,
                            Header = "Şikayet",
                            IconUrl = "/images/icons/icon_complaint.png"
                        },
                        new
                        {
                            Id = 3,
                            ForumGroupId = 2,
                            Header = "Konu-Dışı",
                            IconUrl = ""
                        },
                        new
                        {
                            Id = 4,
                            ForumGroupId = 2,
                            Header = "Çöp",
                            IconUrl = ""
                        },
                        new
                        {
                            Id = 5,
                            ForumGroupId = 3,
                            Header = "Source Sunucuları (SRCDS)",
                            IconUrl = "/images/icons/icon_server.png"
                        },
                        new
                        {
                            Id = 6,
                            ForumGroupId = 3,
                            Header = "HL1 Sunucuları (HLDS)",
                            IconUrl = "/images/icons/icon_server.png"
                        },
                        new
                        {
                            Id = 7,
                            ForumGroupId = 4,
                            Header = "Haberler",
                            IconUrl = "/images/icons/icon_news.png"
                        },
                        new
                        {
                            Id = 8,
                            ForumGroupId = 4,
                            Header = "Genel",
                            IconUrl = "/images/icons/icon_general.png"
                        },
                        new
                        {
                            Id = 9,
                            ForumGroupId = 4,
                            Header = "Eklentiler",
                            IconUrl = "/images/icons/icon_plugin.png"
                        },
                        new
                        {
                            Id = 10,
                            ForumGroupId = 4,
                            Header = "Kodlama",
                            IconUrl = "/images/icons/icon_scripting.png"
                        },
                        new
                        {
                            Id = 11,
                            ForumGroupId = 5,
                            Header = "Haberler",
                            IconUrl = "/images/icons/icon_news.png"
                        },
                        new
                        {
                            Id = 12,
                            ForumGroupId = 5,
                            Header = "Genel",
                            IconUrl = "/images/icons/icon_general.png"
                        },
                        new
                        {
                            Id = 13,
                            ForumGroupId = 5,
                            Header = "Modlar",
                            IconUrl = "/images/icons/icon_mod.png"
                        },
                        new
                        {
                            Id = 14,
                            ForumGroupId = 5,
                            Header = "Kodlama",
                            IconUrl = "/images/icons/icon_scripting.png"
                        });
                });

            modelBuilder.Entity("Entities.ForumGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Header")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ForumGroups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Header = "Sistemler"
                        },
                        new
                        {
                            Id = 2,
                            Header = "Diğer"
                        },
                        new
                        {
                            Id = 3,
                            Header = "Sunucu Tartışmaları"
                        },
                        new
                        {
                            Id = 4,
                            Header = "AMX Mod X"
                        },
                        new
                        {
                            Id = 5,
                            Header = "Minecraft"
                        });
                });

            modelBuilder.Entity("Entities.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Header")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ThreadId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ThreadId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Header = "o sorun çözüldü sanırım ya.",
                            ThreadId = 3
                        },
                        new
                        {
                            Id = 2,
                            Header = "ister olsun ister olmasın para var mı ki oynayabilecez.",
                            ThreadId = 4
                        });
                });

            modelBuilder.Entity("Entities.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Mod sayfasında yer alan \"İndir\" butonuna tıklayarak dosyayı cihazınıza indirebilirsiniz. Giriş yapmanız gerekebilir.",
                            Text = "Modları nasıl indirebilirim?"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Her modun altında, kurulum adımları ayrı bir başlık altında açıklanır. Genel olarak, indirdiğiniz dosyayı oyunun kurulu olduğu klasöre kopyalamanız yeterlidir.",
                            Text = "Modu oyuna nasıl kurabilirim?"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Öncelikle modun oyununuzun sürümüyle uyumlu olup olmadığını kontrol edin. Yine de sorun yaşarsanız ilgili mod başlığında yardım isteyebilirsiniz.",
                            Text = "Bir mod çalışmıyor, ne yapmalıyım?"
                        },
                        new
                        {
                            Id = 4,
                            Description = "\"Mod Paylaş\" bölümüne giderek yeni konu açabilir ve modunuzu dosya olarak ekleyebilirsiniz. Açıklama, kurulum bilgisi ve ekran görüntüsü eklemeniz önerilir.",
                            Text = "Kendi yaptığım modu nasıl paylaşabilirim?"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Telif hakkı ihlali içermeyen, sizin tarafınızdan yapılmış ya da izinle paylaşılan modlar paylaşılabilir. Aksi durumda moderatörler içeriği kaldırabilir.",
                            Text = "Mod paylaşmak yasak mı? Telif sorunları olur mu?"
                        });
                });

            modelBuilder.Entity("Entities.Rule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Rules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Tüm üyelerle nazik ve saygılı bir şekilde iletişim kurun. Hakaret, küfür, alaycı tavırlar yasaktır.",
                            Title = "Saygılı Olun"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Her konuyu doğru kategoriye açın. Konu dışı mesajlar silinebilir veya taşınabilir.",
                            Title = "Konu Dışı Paylaşım Yapmayın"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Yeni bir konu açmadan önce forumda benzer bir konu olup olmadığını kontrol edin.",
                            Title = "Spam ve Reklam Yasaktır"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Yeni bir konu açmadan önce forumda benzer bir konu olup olmadığını kontrol edin.",
                            Title = "Arama Yapmadan Konu Açmayın"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Paylaşımlarınızda telif hakkı ihlali, yasa dışı içerik veya suç teşkil eden ifadeler bulundurmayın.",
                            Title = "Yasalara Uyun"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Forum ortamında küfür, argo, tehdit veya hakaret içeren ifadeler kullanmayın.",
                            Title = "Küfür ve Hakaret Etmeyin"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Kendi veya başkasına ait özel bilgileri (adres, telefon, şifre vb.) paylaşmayın.",
                            Title = "Kişisel Bilgi Paylaşmayın"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Fikir ayrılıkları doğaldır. Tartışmaları kişiselleştirmeyin, yapıcı olun.",
                            Title = "Tartışmalarda Soğukkanlı Kalın"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Forumda sadece bir kullanıcı hesabınız olsun. Çoklu hesaplar yasaktır.",
                            Title = "Tek Hesap Kullanın"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Yöneticiler ve moderatörlerin uyarılarına uymayan kullanıcıların hesapları kısıtlanabilir.",
                            Title = "Yönetici Uyarılarına Uyulmalı"
                        });
                });

            modelBuilder.Entity("Entities.Thread", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ForumId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Header")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ForumId");

                    b.ToTable("Threads");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ForumId = 2,
                            Header = "Birinci şikayet konusu",
                            Text = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus hic ducimus soluta dolorum maiores debitis rerum ut error! Magnam voluptate, excepturi odit laborum natus ad vero sequi tempore. Architecto voluptate perferendis magnam nulla perspiciatis. Tempora quisquam, autem quaerat voluptatum sit, eveniet atque quis tenetur exercitationem voluptatem vero voluptatibus, illo est."
                        },
                        new
                        {
                            Id = 2,
                            ForumId = 2,
                            Header = "İkinci şikayet konusu",
                            Text = "bu şikayet cart curt"
                        },
                        new
                        {
                            Id = 3,
                            ForumId = 1,
                            Header = "forumlardaki gönderilerin gözükmeme sorunu",
                            Text = "kanser etti bu sorun beni, lütfen çözer misiniz?"
                        },
                        new
                        {
                            Id = 4,
                            ForumId = 3,
                            Header = "GTA 6 ne kadar gerçekçi bir oyun olacak?",
                            Text = "Herkesin dilinde şuan, siz ne düşünüyorsunuz?"
                        });
                });

            modelBuilder.Entity("Entities.Forum", b =>
                {
                    b.HasOne("Entities.ForumGroup", "ForumGroup")
                        .WithMany("Forums")
                        .HasForeignKey("ForumGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ForumGroup");
                });

            modelBuilder.Entity("Entities.Post", b =>
                {
                    b.HasOne("Entities.Thread", "Thread")
                        .WithMany("Posts")
                        .HasForeignKey("ThreadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Thread");
                });

            modelBuilder.Entity("Entities.Thread", b =>
                {
                    b.HasOne("Entities.Forum", "Forum")
                        .WithMany("Threads")
                        .HasForeignKey("ForumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Forum");
                });

            modelBuilder.Entity("Entities.Forum", b =>
                {
                    b.Navigation("Threads");
                });

            modelBuilder.Entity("Entities.ForumGroup", b =>
                {
                    b.Navigation("Forums");
                });

            modelBuilder.Entity("Entities.Thread", b =>
                {
                    b.Navigation("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
